package com.st6.weeklycommit.service;

import com.st6.weeklycommit.config.ExportConfig;
import com.st6.weeklycommit.model.dto.DashboardMemberDto;
import com.st6.weeklycommit.model.dto.DashboardTeamDto;
import jakarta.activation.DataSource;
import jakarta.mail.util.ByteArrayDataSource;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
public class EmailExportService {

    private static final Logger log = LoggerFactory.getLogger(EmailExportService.class);

    private final ExportDataService exportDataService;
    private final PdfExportService pdfExportService;
    private final JavaMailSender mailSender;
    private final ExportConfig config;

    public EmailExportService(ExportDataService exportDataService, PdfExportService pdfExportService, Optional<JavaMailSender> mailSender, ExportConfig config) {
        this.exportDataService = exportDataService;
        this.pdfExportService = pdfExportService;
        this.mailSender = mailSender.orElse(null);
        this.config = config;
    }

    public void sendTeamReport(UUID teamId, List<String> recipients, boolean attachPdf) {
        if (mailSender == null) {
            throw new IllegalStateException("Email is not configured. Set spring.mail.host to enable email export.");
        }

        DashboardTeamDto team = exportDataService.getTeamData(teamId);

        String subject = "Weekly Commit Report — " + team.teamName();
        String htmlBody = buildHtmlBody(team);

        try {
            var message = mailSender.createMimeMessage();
            var helper = new MimeMessageHelper(message, attachPdf);
            helper.setFrom(config.getEmailFrom());
            helper.setTo(recipients.toArray(String[]::new));
            helper.setSubject(subject);
            helper.setText(htmlBody, true);

            if (attachPdf) {
                byte[] pdf = pdfExportService.generateTeamReport(teamId);
                DataSource dataSource = new ByteArrayDataSource(pdf, "application/pdf");
                helper.addAttachment("weekly-commit-report.pdf", dataSource);
            }

            mailSender.send(message);
            log.info("Sent export email for team {} to {} recipients", teamId, recipients.size());
        } catch (Exception e) {
            log.error("Failed to send export email for team {}", teamId, e);
            throw new RuntimeException("Failed to send email: " + e.getMessage());
        }
    }

    private String buildHtmlBody(DashboardTeamDto team) {
        StringBuilder sb = new StringBuilder();
        sb.append("<html><body style='font-family: Arial, sans-serif; color: #333;'>");
        sb.append("<h2 style='color: #0f4c5c;'>Weekly Commit Report</h2>");
        sb.append("<h3>").append(team.teamName()).append("</h3>");
        sb.append("<table style='border-collapse: collapse; width: 100%; margin-top: 16px;'>");
        sb.append("<tr style='background: #f0f5fa;'>");
        sb.append("<th style='padding: 8px; text-align: left; border-bottom: 2px solid #ddd;'>Member</th>");
        sb.append("<th style='padding: 8px; text-align: right; border-bottom: 2px solid #ddd;'>Items</th>");
        sb.append("<th style='padding: 8px; text-align: right; border-bottom: 2px solid #ddd;'>SP</th>");
        sb.append("<th style='padding: 8px; text-align: right; border-bottom: 2px solid #ddd;'>Completed</th>");
        sb.append("<th style='padding: 8px; text-align: right; border-bottom: 2px solid #ddd;'>Blocked</th>");
        sb.append("</tr>");

        for (DashboardMemberDto m : team.members()) {
            sb.append("<tr>");
            sb.append("<td style='padding: 8px; border-bottom: 1px solid #eee;'>").append(m.memberName()).append("</td>");
            sb.append("<td style='padding: 8px; text-align: right; border-bottom: 1px solid #eee;'>").append(m.totalItems()).append("</td>");
            sb.append("<td style='padding: 8px; text-align: right; border-bottom: 1px solid #eee;'>").append(m.totalStoryPoints()).append("</td>");
            sb.append("<td style='padding: 8px; text-align: right; border-bottom: 1px solid #eee;'>").append(m.completedStoryPoints()).append("</td>");
            sb.append("<td style='padding: 8px; text-align: right; border-bottom: 1px solid #eee;'>").append(m.blockedItems()).append("</td>");
            sb.append("</tr>");
        }

        sb.append("</table>");
        sb.append("<p style='color: #888; font-size: 12px; margin-top: 24px;'>Generated by ST6 Weekly Commit Module</p>");
        sb.append("</body></html>");
        return sb.toString();
    }
}
